# Generated by Django 2.0.3 on 2018-03-21 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.CharField(max_length=150)),
                ('counter', models.ManyToManyField(related_name='_champion_counter_+', to='champions.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='champion',
            name='lane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.Lane'),
        ),
    ]
