# Generated by Django 2.0.3 on 2018-03-21 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0002_auto_20180321_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passive', models.CharField(max_length=250)),
                ('Q', models.CharField(max_length=250)),
                ('E', models.CharField(max_length=250)),
                ('W', models.CharField(max_length=250)),
                ('R', models.CharField(max_length=250)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.Champion')),
            ],
        ),
    ]
