# Generated by Django 2.0.3 on 2018-03-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0003_ability'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryRunes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rune_class', models.CharField(max_length=20)),
                ('rune_opt_one', models.CharField(max_length=100)),
                ('rune_opt_two', models.CharField(max_length=100)),
                ('rune_opt_three', models.CharField(max_length=100)),
                ('rune_opt_four', models.CharField(max_length=100)),
                ('champion', models.ManyToManyField(related_name='runes', to='champions.Champion')),
            ],
        ),
    ]
