# Generated by Django 2.0.3 on 2018-04-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0004_primaryrunes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrimaryRunes',
            new_name='Runes',
        ),
    ]
